dependencies:
    - python=3.7.7
    - numpy=1.19.2
    - scikit-learn=0.23.2
    - joblib=0.17.0
    - pandas=1.1.3
    - h5py=2.10.0
    - rpy2=2.9.4
    - r-essentials=3.6.0
    - tzlocal=2.1
    - tensorflow=2.3.0
    - keras=2.4.3