sc_priors: Run_Range2UniParameters.py
sc_sfs: Run_Prior2SFS.py
sc_abc: ../Run_SMC.py
sfsfile: ../../examples/YRI_FRN_HAN.observed.csv
priors_range: Oldrange.csv
demography: OOA
inds: 5,5,5
total_length: 1000000
mutation_rate: 1.45e-8
threads: 1
jobs: 10
repeats: 2000
test_size: 1000
improvement: 0.95
tolerance: .1
frac: 0.0015455858426908665
tfknn: ../extras/Dynamic.py