sc_priors: Run_Range2UniParameters.py
sc_sfs: Run_Prior2SFS.py
sc_abc: ../Run_SMC.py
sfsfile: ../../examples/YRI_FRN_HAN.observed.csv
priors_range: Oldrange.csv
hardrange_file : Startrange.csv
demography: OOA
inds: 5,5,5
total_length: 1000000
mutation_rate: 1.45e-8
threads: 1
jobs: 10
repeats: 2000
test_size: 1000
abc_repeats: 10
decrease : 0.95
increase : 0.01
tolerance: .1
frac: 0.0015455858426908665
tfknn: ../extras/Dynamic.py
ldblock: 25e3
resume_nn: True
resume_fit: ../extras/Resume_fit.py
sfs2c: True